####Super Admin ######
##Login##

POST http://localhost:4000/root/login
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password":"admin@123"
}

####Get All Admins ####

GET http://localhost:4000/root/getAllAdmins
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdXBlcmFkbWluIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNjU5MDc5NjQ1LCJleHAiOjE2NTkwODMyNDV9.UQo9fzyQ2Sdkk3ANtd79XB7W89ipG4DGSBtF9HKNhDQ

######Add Admin######
POST http://localhost:4000/root/addAdmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdXBlcmFkbWluIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNjU5MDg0NDA1fQ.IfOQ15o4RbA0H2VX0VzCKGIJSccJp5SxZlohM1wxjUc

{
"email":"admin@admin.com",
"password":"admin@123"
}

####Delete Admin ####
DELETE http://localhost:4000/root/deleteAdmin/62d71002e14c8b7f0ec7e411
Content-Type: application/json


###Logout #####
POST http://localhost:4000/root/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE2NTkwNzYwMTYsImV4cCI6MTY1OTA3OTYxNn0.0bNCryh1zgWsAnhV4XO29O2Ht20jQZ-nKsnuanzDYxo
